import React, { useState } from 'react';
import axios from 'axios';
import '../styles/AIDetectionPage.css';
import Navbar from '../components/Navbar';
import '../styles/Layout.css';

const AIDetectionPage = () => {
  const [text, setText] = useState('');
  const [result, setResult] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    setResult('');

    try {
      const response = await axios.post('http://localhost:8080/api/ia/detect', text, {
        headers: {
          'Content-Type': 'text/plain'
        }
      });
      setResult(response.data);
    } catch (err) {
      setError(err.response?.data || 'An error occurred during analysis');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="layout">
      <Navbar />
      <div className="ai-detection-page">
        <div className="ai-detection-container">
          <h2>AI Content Detection</h2>

          <form onSubmit={handleSubmit}>
            <textarea
              className="text-input"
              placeholder="Enter text to analyze (minimum 500 characters)"
              value={text}
              onChange={(e) => setText(e.target.value)}
              minLength={50}
            />

            <button
              type="submit"
              className="submit-button"
              disabled={loading || text.length < 50}
            >
              {loading ? (
                <>
                  <span className="spinner"></span>
                  Analyzing...
                </>
              ) : (
                'Analyze Text'
              )}
            </button>
          </form>

          {error && (
            <div className="error-message">
              {error}
            </div>
          )}

          {result && (
            console.log('Valeur de result:', result),
            <div className={`result-container ${result === 'IA' ? 'ai-result' : 'human-result'}`}>
              <h3>Analysis Result:</h3>


              <div className="result-text">
                {result === 'IA' ? (
                  <>
                    <span className="result-icon">🤖</span>
                    <span>This text was likely generated by AI</span>
                  </>
                ) : result === 'Humain' ? (
                  <>
                    <span className="result-icon">👤</span>
                    <span>This text was likely written by a human</span>
                  </>
                ) : (
                  <>
                    <span className="result-icon">❓</span>
                    <span>It's unclear whether the text is AI-generated or human-written</span>
                  </>
                )}

              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AIDetectionPage;